server:
  port: 8088

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: "*"

